# Generated by Django 2.2.8 on 2019-12-05 03:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0002_streampage'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='extra',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.CharBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock()), ('product', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('price', wagtail.core.blocks.CharBlock())]))], blank=True),
        ),
    ]
